### PR TITLE
several updates

### PR DESCRIPTION
**Pull request by hrishikeshrt**
- interface updates
    - playback speed control
    - emulate anuccharana mode
- accordion display control through data.json
- mechanism to ignore text written in square brackets in the original text
    - this allows adding shloka numbers etc or other notes
    - known limitation: currently text in bracket should not consider whitespace, if multiple words are to be ignoed each must be enclosed in brackets

Checkout the display at https://hrishikeshrt.github.io/audio_alignment/

### CODE REVIEW

**Comment by shreevatsa** [comment]
I'm just watching this repo and didn't look at the change, but glad to see there's still interest in this :-) Thanks for working on this!

(BTW, one piece of feedback is that when I pointed someone to the website, they were not able to figure out that they need to click on the sidebar on the left: they tried to click on the "Text Source" and "Audio Source" links. Maybe a "Go to first chapter" or "Start playing" link would help…)

**Comment by avinashvarna** [comment]
Thanks Hrishikesh for implementing all these enhancements! I think @shreevatsa's comment is very useful from the perspective of someone visiting the  site for the first time. Along those lines, a couple of quick comments:
- Can we add a tooltip or modal to explain what the various audio controls do?
- I suppose that one of the changes made completely removes the navigation accordion menu on all ashtadhyayi pages. How would a user navigate the website in this case?

**Comment by hrishikeshrt** [comment]
I'll add a help page to explain audio controls soon.
Without accordion interface was developed as a part of another project, that has been implemented for the sake of demonstration, where individual pages were embedded into other pages. Setting `accordion` to `true` in `data.json` will get rid of that. I'll push that change as well.

**Comment by hrishikeshrt** [comment]
Fixed accordion and added help page, which is referenced from the landing page.

**Comment by avinashvarna** [comment]
Thanks! I think it would be nice to have the help linked in the audio controls `<div>` as well, since a direct link to a particular page would bypass the landing page. If you get a chance, please add it to this PR. If not, we can add it later.

I'll open a separate issue if necessary, to address the point that Shreevatsa made about adding a "Go to first chapter" sort of link.

**Comment by hrishikeshrt** [comment]
Added an always on top help icon on every page.
I want to add a "continue to next chapter" link as well (or perhaps even a toggle at the top, "Auto-Advance" that will continue to the next chapter after one chapter is done, but I'll work on it a bit later)

**Comment by avinashvarna** [comment]
Thanks for all the updates!

**Pull request merged**
